CREATE TABLE `athlete-bios` (
  `first_name` text NOT NULL,
  `last_name` text NOT NULL,
  `gender` enum('Female','Male') DEFAULT NULL,
  `sport` text,
  `birth_place` text,
  `age` tinyint(2) unsigned DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `birth_year` int(4) unsigned DEFAULT NULL,
  `birth_month` tinyint(2) unsigned DEFAULT NULL,
  `birth_day` tinyint(2) unsigned DEFAULT NULL,
  `height_meters` decimal(3,2) DEFAULT NULL,
  `height_inches` tinyint(2) unsigned DEFAULT NULL,
  `weight_kg` tinyint(3) unsigned DEFAULT NULL,
  `weight_lbs` tinyint(3) unsigned DEFAULT NULL,
  `team_country` text,
  `residence` text,
  `nationality` text,
  `medals_total` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `medals_gold` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `medals_silver` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `medals_bronze` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `photo` text,
  `url` varchar(255) NOT NULL DEFAULT 'PRIMARY',
  `last_modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`url`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;